Added basic classes
panaman67/OOPProject pull request #28
Opened 2018-04-19 22:55 UTC by unres

2018-04-19 23:46 UTC, panaman67 requested changes
All style stuff, but important

2018-04-19 23:46 UTC, panaman67 commented on orangeChicken.java
> +public class orangeChicken extends Food{
Class name needs to be PascalCase. eg: OrangeChicken

2018-04-19 23:46 UTC, panaman67 commented on orangeChicken.java
> +  public orangeChicken{
Constructor change to match.

2018-04-19 23:46 UTC, panaman67 commented on orangeChicken.java
> +
Make sure spacing is 1 tab (4 spaces equivalent)

2018-04-19 23:46 UTC, panaman67 commented on sweetSourChicken.java
> +public class sweetSourChicken extends food{
Same nits as OrangeChicken

2018-04-23 15:07 UTC, unres commented
Fixed!

2018-04-23 17:25 UTC, panaman67 approved these changes

2018-04-23 17:26 UTC, panaman67 commented
LGTM @unres ! Merging now

2018-04-23 17:26 UTC, merged